name: Setup DPDK and SPDK
description: Install Data Plane Development Kit (DPDK) and Storage Performance Development Kit (SPDK)
inputs:
  dpdk-version:
    description: DPDK version
    required: true
  dpdk-patches:
    description: DPDK patches, comma separated
    required: false
    default: ''
  spdk-version:
    description: SPDK version
    required: false
    default: none
  target-arch:
    description: target architecture
    required: false
    default: x86-64-v3
    # GitHub uses Azure Dadsv5-series with EPYC 7763V processor that satisfies x86-64-v3
    # change to 'native' if using a self-hosted runner for better performance
  setup-hugepages:
    description: hugepages size in MiB
    required: false
    default: 4096
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        DPDKVER: ${{ inputs.dpdk-version }}
        DPDKPATCH: ${{ inputs.dpdk-patches }}
        SPDKVER: ${{ inputs.spdk-version }}
        TARGETARCH: ${{ inputs.target-arch }}
        HUGE: ${{ inputs.setup-hugepages }}
