name: Setup DPDK and SPDK
description: Install Data Plane Development Kit (DPDK) and Storage Performance Development Kit (SPDK)
inputs:
  dpdk-version:
    description: DPDK version
    required: true
  spdk-version:
    description: SPDK version
    required: false
    default: none
  target-arch:
    description: target architecture
    required: false
    default: haswell
    # GitHub uses Azure Standard_DS2_v2, oldest CPU is 'haswell'
    # change to 'native' if using a self-hosted runner
  setup-hugepages:
    description: hugepages size in MiB
    required: false
    default: 4096
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        DPDKVER: ${{ inputs.dpdk-version }}
        SPDKVER: ${{ inputs.spdk-version }}
        TARGETARCH: ${{ inputs.target-arch }}
        HUGE: ${{ inputs.setup-hugepages }}
