name: Setup DPDK and SPDK
description: Install Data Plane Development Kit (DPDK) and Storage Performance Development Kit (SPDK)
inputs:
  dpdk-version:
    description: DPDK version
    required: true
  spdk-version:
    description: SPDK version
    required: true
  target-arch:
    description: target architecture
    required: false
    default: haswell
    # GitHub uses Azure Standard_DS2_v2, oldest CPU is 'haswell'
    # change to 'native' if using a self-hosted runner
  hugepages:
    description: number of 2MB hugepages per NUMA socket
    required: false
    default: 2048
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/main.sh
      shell: bash
      env:
        DPDKVER: ${{ inputs.dpdk-version }}
        SPDKVER: ${{ inputs.spdk-version }}
        NRHUGE: ${{ inputs.hugepages }}
        ARCH: haswell
