name: test
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
        spdk-version:
          - none
          - '22.01'
      fail-fast: false
    env:
      CC: clang
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/setup-dpdk
          key: ${{ matrix.os }}_${{ hashFiles('.github/workflows/*.yml', 'action.yml', 'main.sh') }}
      - name: Run setup-dpdk action
        uses: ./
        with:
          dpdk-version: '22.03'
          spdk-version: ${{ matrix.spdk-version }}
          target-arch: haswell
      - name: List installed files
        run: |
          sudo find /usr/local/bin -name 'dpdk*' -o -name 'spdk*'
          sudo find /usr/local/lib -name 'librte*' -o -name 'libspdk*'
