name: test
on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
          - ubuntu-20.04
        compiler:
          - gcc
          - clang
      fail-fast: false
    env:
      CC: ${{ matrix.compiler }}
    steps:
      - uses: actions/checkout@v2
      - name: install meson
        run: |
          sudo apt install meson
      - uses: actions/cache@v2
        with:
          path: |
            ~/setup-dpdk
          key: ${{ matrix.os }}_${{ matrix.compiler }}_${{ hashFiles('.github/workflows/*.yml', 'action.yml', 'main.sh') }}
      - uses: ./
        with:
          dpdk-version: '21.02'
          spdk-version: '21.01.1'
          target-arch: haswell
      - name: list installed files
        run: |
          sudo find /usr/local/bin -name 'dpdk*' -o -name 'spdk*'
          sudo find /usr/local/lib -name 'librte_*' -o -name 'libspdk_*'
