name: test
on:
  push:
    branches:
      - develop
  pull_request:
  workflow_dispatch:
permissions: {}
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-22.04
        dpdk-version:
          - v23.03
        dpdk-patches:
          - ''
        spdk-version:
          - none
          - v23.05
        include:
          - os: ubuntu-22.04
            dpdk-version: v22.11
            dpdk-patches: 26031
            spdk-version: 5497616e8ff768313a441980d44f439558509b4f
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      CC: clang
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/setup-dpdk
          key: ${{ matrix.os }}_${{ matrix.dpdk-version }}_${{ matrix.dpdk-patches }}_${{ matrix.spdk-version }}_${{ hashFiles('.github/workflows/*.yml', 'action.yml', 'main.sh') }}
      - name: Run setup-dpdk action
        uses: ./
        with:
          dpdk-version: ${{ matrix.dpdk-version }}
          dpdk-patches: ${{ matrix.dpdk-patches }}
          spdk-version: ${{ matrix.spdk-version }}
      - name: List installed files
        run: |
          find /usr/local/bin -name 'dpdk*' -o -name 'spdk*'
          find /usr/local/lib -name 'librte*' -o -name 'libspdk*'
